#Build image for mini_finance website 
FROM ubuntu:latest AS BUILD_IMAGE
RUN apt update && apt install wget unzip -y && \
    wget https://www.tooplate.com/zip-templates/2135_mini_finance.zip && \
    unzip -o 2135_mini_finance.zip

#Build image for nginx    
FROM nginx:latest
COPY --from=BUILD_IMAGE /2135_mini_finance /usr/share/nginx/html
EXPOSE 80

